import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for push notifications
self.addEventListener('push', function (event) {
  if (event.data) {
    try {
      const data = event.data.json();
      
      const options = {
        body: data.body,
        icon: '/vseva-logo.png',
        badge: '/pwa-192x192.png',
        vibrate: [200, 100, 200, 100, 200, 100, 200],
        data: data.data || { url: '/' },
        // Actions can be added here if needed
      };

      event.waitUntil(
        self.registration.showNotification(data.title || 'vSeva Notification', options)
      );
    } catch (e) {
      console.error('Error parsing push payload', e);
      // Fallback
      event.waitUntil(
        self.registration.showNotification('vSeva Notification', {
          body: event.data.text(),
          icon: '/vseva-logo.png'
        })
      );
    }
  }
});

// Handle notification clear/click events
self.addEventListener('notificationclick', function(event) {
  event.notification.close();

  const urlToOpen = new URL(event.notification.data?.url || '/', self.location.origin).href;

  event.waitUntil(
    self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true
    }).then(function(windowClients) {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        // If so, just focus it.
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If not, then open the target URL in a new window/tab.
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
