import { precacheAndRoute } from 'workbox-precaching';

// OneSignal Integration
// @ts-ignore
importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js');

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

/* 
// Legacy Push Listeners (Replaced by OneSignal)
self.addEventListener('push', function (event) {
  // ... (commented out)
});

self.addEventListener('notificationclick', function(event) {
  // ... (commented out)
});
*/
