import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim, skipWaiting } from 'workbox-core';

// OneSignal Integration
// @ts-ignore
importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js');

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// skipWaiting() makes the new SW activate immediately upon detection,
// bypassing the waiting phase. This ensures that every time you push
// a new deployment, installed PWA users get the update automatically
// on their next page visibility/load — no manual "Update App" tap needed.
skipWaiting();

// clientsClaim() makes the newly active SW take control of all open tabs
// right away, so the updated assets are served immediately.
clientsClaim();
