// Generates the Shraman Seva Group Android resources (launcher icons, splash screens, notification icon) into
// android/app/src/ssg/res/ — the folder Gradle layers over src/main/res when the `ssg` flavor is built.
// The output is committed (builds never run this); re-run it only if the SSG logo changes:
//
//   node scripts/prepare_android_ssg_assets.mjs
//
// Source: brands/ssg/public/pwa-512x512.png (the SSG app icon: sunrise emblem on white).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'brands/ssg/public/pwa-512x512.png');
const out = path.join(root, 'android/app/src/ssg/res');
const WHITE = { r: 255, g: 255, b: 255, alpha: 1 };

// The PWA icon has a wide white margin; trim it so the emblem fills the launcher icon properly, then re-pad to a
// square with a small margin. Everything below is made from this one buffer.
const trimmed = await sharp(src).trim({ background: '#ffffff', threshold: 12 }).toBuffer({ resolveWithObject: true });
const side = Math.round(Math.max(trimmed.info.width, trimmed.info.height) * 1.1);
const emblem = await sharp({ create: { width: side, height: side, channels: 4, background: WHITE } })
  .composite([{ input: trimmed.data, gravity: 'centre' }])
  .png()
  .toBuffer();

const write = async (rel, pipeline) => {
  const file = path.join(out, rel);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  await pipeline.png().toFile(file);
};

// --- launcher icons -------------------------------------------------------------------------------------------
// legacy icon (dp 48), round variant, and the two adaptive layers (dp 108; the adaptive xml insets them 16.7%,
// exactly like the vSeva icons generated by @capacitor/assets).
const DENSITIES = { mdpi: [48, 108], hdpi: [72, 162], xhdpi: [96, 216], xxhdpi: [144, 324], xxxhdpi: [192, 432] };
for (const [name, [icon, layer]] of Object.entries(DENSITIES)) {
  const dir = `mipmap-${name}`;
  await write(`${dir}/ic_launcher.png`, sharp(emblem).resize(icon, icon).flatten({ background: WHITE }));
  const circle = Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${icon}" height="${icon}"><circle cx="${icon / 2}" cy="${icon / 2}" r="${icon / 2}"/></svg>`);
  await write(`${dir}/ic_launcher_round.png`, sharp(emblem).resize(icon, icon).flatten({ background: WHITE }).composite([{ input: circle, blend: 'dest-in' }]));
  await write(`${dir}/ic_launcher_foreground.png`, sharp(emblem).resize(layer, layer).flatten({ background: WHITE }));
  await write(`${dir}/ic_launcher_background.png`, sharp({ create: { width: layer, height: layer, channels: 4, background: WHITE } }));
}

// --- splash screens (same sizes as the vSeva ones; the emblem centred on white) --------------------------------
const SPLASH = {
  'drawable/splash.png': [320, 480],
  'drawable-port-mdpi/splash.png': [320, 480], 'drawable-port-hdpi/splash.png': [480, 800], 'drawable-port-xhdpi/splash.png': [720, 1280],
  'drawable-port-xxhdpi/splash.png': [960, 1600], 'drawable-port-xxxhdpi/splash.png': [1280, 1920],
  'drawable-land-mdpi/splash.png': [480, 320], 'drawable-land-hdpi/splash.png': [800, 480], 'drawable-land-xhdpi/splash.png': [1280, 720],
  'drawable-land-xxhdpi/splash.png': [1600, 960], 'drawable-land-xxxhdpi/splash.png': [1920, 1280],
};
for (const [rel, [w, h]] of Object.entries(SPLASH)) {
  const size = Math.round(Math.min(w, h) * 0.5);
  const logo = await sharp(emblem).resize(size, size).flatten({ background: WHITE }).toBuffer();
  await write(rel, sharp({ create: { width: w, height: h, channels: 4, background: WHITE } })
    .composite([{ input: logo, left: Math.round((w - size) / 2), top: Math.round((h - size) / 2) }]));
}

// --- notification small icon: a white silhouette of the emblem (Android tints/uses only its alpha) -------------
{
  const N = 48;
  const raw = await sharp(emblem).resize(N - 8, N - 8).flatten({ background: WHITE }).raw().toBuffer({ resolveWithObject: true });
  const { data, info } = raw;
  const rgba = Buffer.alloc(N * N * 4); // transparent
  for (let y = 0; y < info.height; y++) {
    for (let x = 0; x < info.width; x++) {
      const i = (y * info.width + x) * info.channels;
      const nonWhite = data[i] < 235 || data[i + 1] < 235 || data[i + 2] < 235;
      const o = ((y + 4) * N + (x + 4)) * 4;
      rgba[o] = rgba[o + 1] = rgba[o + 2] = 255;
      rgba[o + 3] = nonWhite ? 255 : 0;
    }
  }
  await write('drawable/ic_stat_onesignal_default.png', sharp(rgba, { raw: { width: N, height: N, channels: 4 } }));
}

console.log('SSG Android resources written to', path.relative(root, out));
